language: c



compiler:

  - gcc
  
before_install:

  - sudo apt-get update
  
  
  
install:

  - echo "Reached Install Section"
  
script:
  - echo "Reached Script Section"
  - gcc   hello_world.c -o output
  - ./output
